# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'adjust.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QSlider, QWidget)

class Ui_adjust(object):
    def setupUi(self, adjust):
        if not adjust.objectName():
            adjust.setObjectName(u"adjust")
        adjust.resize(600, 350)
        adjust.setMinimumSize(QSize(600, 350))
        adjust.setMaximumSize(QSize(600, 350))
        self.centralwidget = QWidget(adjust)
        self.centralwidget.setObjectName(u"centralwidget")
        self.slider_1 = QSlider(self.centralwidget)
        self.slider_1.setObjectName(u"slider_1")
        self.slider_1.setGeometry(QRect(140, 10, 401, 31))
        self.slider_1.setMinimum(-255)
        self.slider_1.setMaximum(255)
        self.slider_1.setOrientation(Qt.Horizontal)
        self.slider_1.setInvertedAppearance(False)
        self.slider_1.setInvertedControls(False)
        self.slider_1.setTickPosition(QSlider.TicksBothSides)
        self.label_1 = QLabel(self.centralwidget)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(11, 15, 121, 20))
        font = QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setAlignment(Qt.AlignCenter)
        self.label_1.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(11, 115, 121, 20))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setTextInteractionFlags(Qt.NoTextInteraction)
        self.slider_3 = QSlider(self.centralwidget)
        self.slider_3.setObjectName(u"slider_3")
        self.slider_3.setGeometry(QRect(140, 110, 401, 31))
        self.slider_3.setMinimum(-255)
        self.slider_3.setMaximum(255)
        self.slider_3.setOrientation(Qt.Horizontal)
        self.slider_3.setInvertedAppearance(False)
        self.slider_3.setInvertedControls(False)
        self.slider_3.setTickPosition(QSlider.TicksBothSides)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(11, 65, 121, 20))
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(Qt.NoTextInteraction)
        self.slider_2 = QSlider(self.centralwidget)
        self.slider_2.setObjectName(u"slider_2")
        self.slider_2.setGeometry(QRect(140, 60, 401, 31))
        self.slider_2.setMinimum(-255)
        self.slider_2.setMaximum(255)
        self.slider_2.setOrientation(Qt.Horizontal)
        self.slider_2.setInvertedAppearance(False)
        self.slider_2.setInvertedControls(False)
        self.slider_2.setTickPosition(QSlider.TicksBothSides)
        self.render = QPushButton(self.centralwidget)
        self.render.setObjectName(u"render")
        self.render.setGeometry(QRect(340, 300, 89, 24))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(11, 165, 121, 20))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setTextInteractionFlags(Qt.NoTextInteraction)
        self.slider_4 = QSlider(self.centralwidget)
        self.slider_4.setObjectName(u"slider_4")
        self.slider_4.setGeometry(QRect(140, 160, 401, 31))
        self.slider_4.setMinimum(-255)
        self.slider_4.setMaximum(255)
        self.slider_4.setOrientation(Qt.Horizontal)
        self.slider_4.setInvertedAppearance(False)
        self.slider_4.setInvertedControls(False)
        self.slider_4.setTickPosition(QSlider.TicksBothSides)
        self.invert = QCheckBox(self.centralwidget)
        self.invert.setObjectName(u"invert")
        self.invert.setGeometry(QRect(170, 300, 93, 21))
        self.contrast_slider = QSlider(self.centralwidget)
        self.contrast_slider.setObjectName(u"contrast_slider")
        self.contrast_slider.setGeometry(QRect(140, 260, 401, 25))
        self.contrast_slider.setMinimum(0)
        self.contrast_slider.setMaximum(300)
        self.contrast_slider.setSliderPosition(100)
        self.contrast_slider.setOrientation(Qt.Horizontal)
        self.contrast_slider.setInvertedAppearance(False)
        self.contrast_slider.setInvertedControls(False)
        self.contrast_slider.setTickPosition(QSlider.TicksBothSides)
        self.contrast_label = QLabel(self.centralwidget)
        self.contrast_label.setObjectName(u"contrast_label")
        self.contrast_label.setGeometry(QRect(10, 260, 121, 20))
        self.contrast_label.setFont(font)
        self.contrast_label.setAlignment(Qt.AlignCenter)
        self.contrast_label.setTextInteractionFlags(Qt.NoTextInteraction)
        self.brightness_slider = QSlider(self.centralwidget)
        self.brightness_slider.setObjectName(u"brightness_slider")
        self.brightness_slider.setGeometry(QRect(140, 210, 401, 25))
        self.brightness_slider.setMinimum(0)
        self.brightness_slider.setMaximum(300)
        self.brightness_slider.setSliderPosition(100)
        self.brightness_slider.setOrientation(Qt.Horizontal)
        self.brightness_slider.setInvertedAppearance(False)
        self.brightness_slider.setInvertedControls(False)
        self.brightness_slider.setTickPosition(QSlider.TicksBothSides)
        self.brightness_label = QLabel(self.centralwidget)
        self.brightness_label.setObjectName(u"brightness_label")
        self.brightness_label.setGeometry(QRect(10, 210, 121, 20))
        self.brightness_label.setFont(font)
        self.brightness_label.setAlignment(Qt.AlignCenter)
        self.brightness_label.setTextInteractionFlags(Qt.NoTextInteraction)
        self.reset_1 = QPushButton(self.centralwidget)
        self.reset_1.setObjectName(u"reset_1")
        self.reset_1.setGeometry(QRect(550, 15, 41, 24))
        self.reset_2 = QPushButton(self.centralwidget)
        self.reset_2.setObjectName(u"reset_2")
        self.reset_2.setGeometry(QRect(550, 60, 41, 30))
        self.reset_3 = QPushButton(self.centralwidget)
        self.reset_3.setObjectName(u"reset_3")
        self.reset_3.setGeometry(QRect(550, 110, 41, 30))
        self.reset_4 = QPushButton(self.centralwidget)
        self.reset_4.setObjectName(u"reset_4")
        self.reset_4.setGeometry(QRect(550, 160, 41, 24))
        self.brightness_reset = QPushButton(self.centralwidget)
        self.brightness_reset.setObjectName(u"brightness_reset")
        self.brightness_reset.setGeometry(QRect(550, 210, 41, 24))
        self.contrast_reset = QPushButton(self.centralwidget)
        self.contrast_reset.setObjectName(u"contrast_reset")
        self.contrast_reset.setGeometry(QRect(550, 260, 41, 24))
        adjust.setCentralWidget(self.centralwidget)

        self.retranslateUi(adjust)

        QMetaObject.connectSlotsByName(adjust)
    # setupUi

    def retranslateUi(self, adjust):
        adjust.setWindowTitle(QCoreApplication.translate("adjust", u"\u8c03\u8272\u5668", None))
        self.label_1.setText(QCoreApplication.translate("adjust", u"  \u504f\u79fb\u91cf\uff1a0", None))
        self.label_3.setText(QCoreApplication.translate("adjust", u"  \u504f\u79fb\u91cf\uff1a0", None))
        self.label_2.setText(QCoreApplication.translate("adjust", u"  \u504f\u79fb\u91cf\uff1a0", None))
        self.render.setText(QCoreApplication.translate("adjust", u"\u9884\u89c8", None))
        self.label_4.setText(QCoreApplication.translate("adjust", u"  \u504f\u79fb\u91cf\uff1a0", None))
        self.invert.setText(QCoreApplication.translate("adjust", u"\u53cd\u8f6c\u989c\u8272", None))
        self.contrast_label.setText(QCoreApplication.translate("adjust", u"\u5bf9\u6bd4\u5ea6\uff1a100%", None))
        self.brightness_label.setText(QCoreApplication.translate("adjust", u"\u4eae\u5ea6\uff1a100%", None))
        self.reset_1.setText(QCoreApplication.translate("adjust", u"\u91cd\u7f6e", None))
        self.reset_2.setText(QCoreApplication.translate("adjust", u"\u91cd\u7f6e", None))
        self.reset_3.setText(QCoreApplication.translate("adjust", u"\u91cd\u7f6e", None))
        self.reset_4.setText(QCoreApplication.translate("adjust", u"\u91cd\u7f6e", None))
        self.brightness_reset.setText(QCoreApplication.translate("adjust", u"\u91cd\u7f6e", None))
        self.contrast_reset.setText(QCoreApplication.translate("adjust", u"\u91cd\u7f6e", None))
    # retranslateUi

