# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_gui(object):
    def setupUi(self, gui):
        if gui.objectName():
            gui.setObjectName(u"gui")
        gui.resize(720, 405)
        gui.setMinimumSize(QSize(720, 405))
        gui.setMaximumSize(QSize(720, 405))
        self.centralwidget = QWidget(gui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.name_label = QLabel(self.centralwidget)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setGeometry(QRect(290, 50, 150, 25))
        self.name_label.setMinimumSize(QSize(150, 25))
        font = QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setAutoFillBackground(True)
        self.name_label.setAlignment(Qt.AlignCenter)
        self.title_label = QLabel(self.centralwidget)
        self.title_label.setObjectName(u"title_label")
        self.title_label.setGeometry(QRect(160, 10, 400, 41))
        self.title_label.setMinimumSize(QSize(400, 0))
        self.title_label.setBaseSize(QSize(100, 0))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        font1.setWeight(75)
        self.title_label.setFont(font1)
        self.title_label.setAutoFillBackground(True)
        self.title_label.setAlignment(Qt.AlignCenter)
        self.filter_mode = QComboBox(self.centralwidget)
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.addItem("")
        self.filter_mode.setObjectName(u"filter_mode")
        self.filter_mode.setGeometry(QRect(30, 110, 181, 41))
        self.filter_mode.setFont(font)
        self.choose = QPushButton(self.centralwidget)
        self.choose.setObjectName(u"choose")
        self.choose.setGeometry(QRect(30, 70, 91, 31))
        self.path = QLabel(self.centralwidget)
        self.path.setObjectName(u"path")
        self.path.setGeometry(QRect(130, 70, 561, 31))
        font2 = QFont()
        font2.setPointSize(8)
        self.path.setFont(font2)
        self.path.setAlignment(Qt.AlignCenter)
        self.render = QPushButton(self.centralwidget)
        self.render.setObjectName(u"render")
        self.render.setGeometry(QRect(590, 100, 121, 31))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        self.render.setFont(font3)
        self.before = QLabel(self.centralwidget)
        self.before.setObjectName(u"before")
        self.before.setGeometry(QRect(0, 160, 360, 240))
        self.before.setFont(font1)
        self.before.setAlignment(Qt.AlignCenter)
        self.after = QLabel(self.centralwidget)
        self.after.setObjectName(u"after")
        self.after.setGeometry(QRect(360, 160, 360, 240))
        self.after.setFont(font1)
        self.after.setAlignment(Qt.AlignCenter)
        self.color_mode = QComboBox(self.centralwidget)
        self.color_mode.addItem("")
        self.color_mode.addItem("")
        self.color_mode.setObjectName(u"color_mode")
        self.color_mode.setGeometry(QRect(250, 110, 71, 41))
        self.color_mode.setFont(font)
        self.width_limit = QSpinBox(self.centralwidget)
        self.width_limit.setObjectName(u"width_limit")
        self.width_limit.setGeometry(QRect(360, 110, 91, 41))
        self.width_limit.setMinimum(1)
        self.width_limit.setMaximum(999999)
        self.height_limit = QSpinBox(self.centralwidget)
        self.height_limit.setObjectName(u"height_limit")
        self.height_limit.setGeometry(QRect(460, 110, 91, 41))
        self.height_limit.setMinimum(1)
        self.height_limit.setMaximum(999999)
        self.save = QPushButton(self.centralwidget)
        self.save.setObjectName(u"save")
        self.save.setGeometry(QRect(590, 130, 121, 31))
        self.save.setFont(font3)
        gui.setCentralWidget(self.centralwidget)

        self.retranslateUi(gui)

        QMetaObject.connectSlotsByName(gui)
    # setupUi

    def retranslateUi(self, gui):
        gui.setWindowTitle(QCoreApplication.translate("gui", u"\u795e\u9f99\u56fe\u7247\u5904\u7406 v1.0", None))
        self.name_label.setText(QCoreApplication.translate("gui", u"by abcdesteve", None))
        self.title_label.setText(QCoreApplication.translate("gui", u"\u795e\u9f99\u56fe\u7247\u5904\u7406 v1.0", None))
        self.filter_mode.setItemText(0, QCoreApplication.translate("gui", u"\u9009\u62e9\u6ee4\u955c", None))
        self.filter_mode.setItemText(1, QCoreApplication.translate("gui", u"BLUR", None))
        self.filter_mode.setItemText(2, QCoreApplication.translate("gui", u"CONTOUR", None))
        self.filter_mode.setItemText(3, QCoreApplication.translate("gui", u"DETAIL", None))
        self.filter_mode.setItemText(4, QCoreApplication.translate("gui", u"EDGE_ENHANCE", None))
        self.filter_mode.setItemText(5, QCoreApplication.translate("gui", u"EDGE_ENHANCE_MORE", None))
        self.filter_mode.setItemText(6, QCoreApplication.translate("gui", u"EMBOSS", None))
        self.filter_mode.setItemText(7, QCoreApplication.translate("gui", u"FIND_EDGES", None))
        self.filter_mode.setItemText(8, QCoreApplication.translate("gui", u"GaussianBlur", None))
        self.filter_mode.setItemText(9, QCoreApplication.translate("gui", u"SHARPEN", None))
        self.filter_mode.setItemText(10, QCoreApplication.translate("gui", u"SMOOTH", None))
        self.filter_mode.setItemText(11, QCoreApplication.translate("gui", u"SMOOTH_MORE", None))
        self.filter_mode.setItemText(12, QCoreApplication.translate("gui", u"UnsharpMask", None))
        self.filter_mode.setItemText(13, QCoreApplication.translate("gui", u"\u7d20\u63cf\u6ee4\u955c", None))
        self.filter_mode.setItemText(14, QCoreApplication.translate("gui", u"\u5b57\u7b26\u753b\u6ee4\u955c", None))

        self.choose.setText(QCoreApplication.translate("gui", u"\u9009\u62e9\u56fe\u7247", None))
        self.path.setText(QCoreApplication.translate("gui", u"\u56fe\u7247\u8def\u5f84", None))
        self.render.setText(QCoreApplication.translate("gui", u"\u5f00\u59cb\u5904\u7406", None))
        self.before.setText(QCoreApplication.translate("gui", u"\u5904\u7406\u524d(\u5df2\u7f29\u653e)", None))
        self.after.setText(QCoreApplication.translate("gui", u"\u5904\u7406\u540e(\u5df2\u7f29\u653e)", None))
        self.color_mode.setItemText(0, QCoreApplication.translate("gui", u"RGBA", None))
        self.color_mode.setItemText(1, QCoreApplication.translate("gui", u"L", None))

        self.save.setText(QCoreApplication.translate("gui", u"\u4fdd\u5b58\u7ed3\u679c", None))
    # retranslateUi

